import { useEffect, useMemo, useState } from 'react'
import { AlertTriangle, CheckCircle2, Cpu, Gauge, ServerCog, Trophy } from 'lucide-react'
import Chart from '../components/Chart'
import { api, query, type Filters } from '../services/api'

type Row = Record<string, any>
const MODELS = ['persistence', 'random_forest', 'xgboost', 'lightgbm', 'prophet', 'lstm', 'gru', 'tft']
const COLORS = ['#0fa97b', '#4779d8', '#f0a43b', '#b85dc5', '#e05f5f', '#64756e']
const modelName = (value: string) => value.replaceAll('_', ' ').replace(/\b\w/g, letter => letter.toUpperCase())
const fmt = (value: unknown, digits = 3) => value == null || value === '' || (typeof value === 'number' && !Number.isFinite(value)) ? '—' : typeof value === 'number' ? value.toLocaleString(undefined, { maximumFractionDigits: digits }) : String(value)

function Panel({ eyebrow, title, children }: { eyebrow: string; title: string; children: React.ReactNode }) { return <section className="card"><div className="card-head"><div><span className="eyebrow">{eyebrow}</span><h3>{title}</h3></div></div>{children}</section> }
function Table({ rows, columns }: { rows: Row[]; columns: [string, string][] }) { return <div className="table-wrap"><table><thead><tr>{columns.map(([, label]) => <th key={label}>{label}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr key={index}>{columns.map(([key]) => <td key={key}>{key === 'model' ? <strong>{modelName(row[key])}</strong> : fmt(row[key])}</td>)}</tr>)}</tbody></table></div> }

export default function ModelBenchmarking({ filters }: { filters: Filters }) {
  const [results, setResults] = useState<Row | null>(null), [leaderboard, setLeaderboard] = useState<Row>({})
  const [model, setModel] = useState('lightgbm'), [horizon, setHorizon] = useState('1h')
  const [detail, setDetail] = useState<Row | null>(null), [predictions, setPredictions] = useState<Row>({ items: [] }), [error, setError] = useState('')
  useEffect(() => { Promise.all([api<Row>('/api/models/results'), api<Row>('/api/models/leaderboard')]).then(([r, l]) => { setResults(r); setLeaderboard(l) }).catch(err => setError(err.message)) }, [])
  useEffect(() => { Promise.all([api<Row>(`/api/models/${model}`), api<Row>(`/api/models/${model}/predictions${query({ horizon, split: 'test', sensor_id: filters.sensorId, max_points: 1400 })}`)]).then(([d, p]) => { setDetail(d); setPredictions(p); setError('') }).catch(err => { setDetail(null); setPredictions({ items: [] }); setError(err.message) }) }, [model, horizon, filters.sensorId])
  const rows = predictions.items || [], selected = detail?.summary?.horizons?.[horizon] || {}, realtime = detail?.realtime || {}
  const detailOverall = detail?.details?.find((row: Row) => row.horizon === horizon && row.sensor_scope === 'all')
  const metricRows = useMemo(() => MODELS.map(item => { const data = results?.models?.[item] || {}, horizons = data.horizons || {}; return { model: item, rmse_1h: horizons['1h']?.rmse, rmse_3h: horizons['3h']?.rmse, rmse_6h: horizons['6h']?.rmse, mae: horizons[horizon]?.mae, r2: horizons[horizon]?.r2, event_recall: horizons[horizon]?.event_recall, event_f1: horizons[horizon]?.event_f1, status: data.status || 'not run' } }), [results, horizon])
  const sensorRows = (detail?.details || []).filter((row: Row) => row.horizon === horizon && row.sensor_scope !== 'all').map((row: Row) => ({ sensor: row.sensor_scope.replace('sensor_', ''), city: row.metrics.city, n: row.metrics.n, rmse: row.metrics.rmse, mae: row.metrics.mae, r2: row.metrics.r2, recall: row.metrics.event_recall, status: row.metrics.status }))
  if (!results) return <div className="advanced-loading"><span /><p>Loading saved model benchmarks…</p></div>
  const actualMax = Math.max(1, ...rows.map((row: Row) => Number(row.actual) || 0))
  return <div className="model-stack">
    <div className="model-heading"><div><Trophy /><span>AirAware Phase 4A</span><h2>Individual Model Benchmarking</h2><p>Chronological unseen-test evidence only. No ensemble or stacking output.</p></div><div className="phase-chip"><CheckCircle2 /> Saved local results</div></div>
    <div className="model-controls"><label className="inline-control"><span>Model</span><select value={model} onChange={e => setModel(e.target.value)}>{MODELS.map(item => <option value={item} key={item}>{modelName(item)}</option>)}</select></label><label className="inline-control"><span>Horizon</span><select value={horizon} onChange={e => setHorizon(e.target.value)}><option value="1h">1 hour</option><option value="3h">3 hours</option><option value="6h">6 hours</option></select></label><div className={`baseline-verdict ${detailOverall?.beats_persistence ? 'yes' : 'no'}`}><span>Beats Persistence</span><strong>{model === 'persistence' ? 'Baseline' : detailOverall?.beats_persistence ? 'Yes' : 'No'}</strong></div></div>
    {error && <div className="callout"><AlertTriangle /><div><strong>Saved result unavailable</strong><p>{error}</p></div></div>}
    <div className="model-kpis"><article><span>RMSE</span><strong>{fmt(selected.rmse)}</strong><small>{horizon} test</small></article><article><span>MAE</span><strong>{fmt(selected.mae)}</strong><small>µg/m³</small></article><article><span>R²</span><strong>{fmt(selected.r2)}</strong><small>newest unseen period</small></article><article><span>Event Recall</span><strong>{fmt(selected.event_recall)}</strong><small>False negatives: {fmt(selected.false_negatives, 0)}</small></article></div>
    <Panel eyebrow="Overall evidence" title="Model leaderboard"><Table rows={metricRows} columns={[["model", "Model"], ["rmse_1h", "1h RMSE"], ["rmse_3h", "3h RMSE"], ["rmse_6h", "6h RMSE"], ["mae", `${horizon} MAE`], ["r2", "R²"], ["event_recall", "Event Recall"], ["event_f1", "Event F1"], ["status", "Status"]]} /></Panel>
    <div className="grid-two model-chart-grid"><Panel eyebrow="Test time series" title="Actual vs predicted"><Chart data={[{ type: 'scattergl', mode: 'lines', x: rows.map((r: Row) => r.timestamp), y: rows.map((r: Row) => r.actual), name: 'Actual', line: { color: '#263f36' } }, { type: 'scattergl', mode: 'lines', x: rows.map((r: Row) => r.timestamp), y: rows.map((r: Row) => r.predicted), name: modelName(model), line: { color: '#0fa97b' } }]} layout={{ height: 360, yaxis: { title: { text: 'PM2.5 (µg/m³)' } } }} /></Panel><Panel eyebrow="Calibration" title="Predicted vs actual"><Chart data={[{ type: 'scattergl', mode: 'markers', x: rows.map((r: Row) => r.actual), y: rows.map((r: Row) => r.predicted), marker: { color: '#4779d8', opacity: .45, size: 5 } }, { type: 'scatter', mode: 'lines', x: [0, actualMax], y: [0, actualMax], name: 'Ideal', line: { color: '#d95d5d', dash: 'dash' } }]} layout={{ height: 360, hovermode: 'closest', xaxis: { title: { text: 'Actual' } }, yaxis: { title: { text: 'Predicted' } } }} /></Panel></div>
    <div className="grid-two model-chart-grid"><Panel eyebrow="Error shape" title="Residual distribution"><Chart data={[{ type: 'histogram', x: rows.map((r: Row) => r.residual), nbinsx: 40, marker: { color: '#f0a43b' } }]} layout={{ height: 310, xaxis: { title: { text: 'Actual − predicted' } } }} /></Panel><Panel eyebrow="Drift check" title="Error over time"><Chart data={[{ type: 'scattergl', mode: 'markers', x: rows.map((r: Row) => r.timestamp), y: rows.map((r: Row) => r.residual), marker: { color: '#b85dc5', size: 4, opacity: .6 } }]} layout={{ height: 310, yaxis: { title: { text: 'Residual' }, zeroline: true } }} /></Panel></div>
    <div className="grid-two"><Panel eyebrow="Horizon comparison" title="RMSE by forecast horizon"><Chart data={[{ type: 'bar', x: ['1h', '3h', '6h'], y: ['1h', '3h', '6h'].map(item => detail?.summary?.horizons?.[item]?.rmse), marker: { color: COLORS } }]} layout={{ height: 300, yaxis: { title: { text: 'RMSE' } } }} /></Panel><Panel eyebrow="Per-sensor test" title="Sensor performance"><Table rows={sensorRows} columns={[["sensor", "Sensor"], ["city", "City"], ["n", "N"], ["rmse", "RMSE"], ["mae", "MAE"], ["r2", "R²"], ["recall", "Recall"], ["status", "Status"]]} /></Panel></div>
    {!!detail?.feature_importance?.[horizon]?.length && <Panel eyebrow="Explainability" title="Native feature importance"><Chart data={[{ type: 'bar', orientation: 'h', y: detail.feature_importance[horizon].slice(0, 15).reverse().map((r: Row) => r.feature), x: detail.feature_importance[horizon].slice(0, 15).reverse().map((r: Row) => r.importance), marker: { color: '#0fa97b' } }]} layout={{ height: 410, margin: { l: 190 } }} /></Panel>}
    {!!detail?.training_history?.[horizon]?.length && <Panel eyebrow="Training progress" title="Training and validation loss"><Chart data={[{ type: 'scatter', mode: 'lines+markers', x: detail.training_history[horizon].map((r: Row) => r.epoch), y: detail.training_history[horizon].map((r: Row) => r.training_loss), name: 'Training', line: { color: '#0fa97b' } }, { type: 'scatter', mode: 'lines+markers', x: detail.training_history[horizon].map((r: Row) => r.epoch), y: detail.training_history[horizon].map((r: Row) => r.validation_loss), name: 'Validation', line: { color: '#e05f5f' } }]} layout={{ height: 320 }} /></Panel>}
    <div className="grid-two"><Panel eyebrow="Deployment evidence" title="Real-time replay"><div className="deployment-facts"><span><Cpu />Average inference<strong>{fmt(realtime.average_inference_ms)} ms</strong></span><span><Gauge />P95 inference<strong>{fmt(realtime.p95_inference_ms)} ms</strong></span><span><ServerCog />Model size<strong>{fmt(realtime.model_size_mb)} MB</strong></span><span><CheckCircle2 />Minimum history<strong>{realtime.minimum_history_required || 'Pending replay'}</strong></span></div></Panel><Panel eyebrow="Current ranking" title={`${horizon} RMSE order`}><Table rows={leaderboard?.[horizon]?.rmse || []} columns={[["rank", "Rank"], ["model", "Model"], ["rmse", "RMSE"]]} /></Panel></div>
  </div>
}
